language: php

notifications:
  email:
    on_success: never

env:
  global:
    secure: "EhS3yREhaexpuqfM7+AdbCZJ6ES8dErEp7PJUuTLZ24Xh3XGCtcWALWmpFhXsUXtO7AcA4amyFEGkP50gav5kwdCjsl7nQDqEMmvvRsQPpfxxFmfg27etxFZdQ2rc5nByzpmYoVzP0WC9rc37AhYwZnHyZuz+QpCb6MNvJ6ObyP6u+HVqn90VNM+i2IT9efcLutsUFCdk7r8tii0n08u4eiRRtK43SL0lSlduBdh9yse0BL86+RgSlZ0nEaYFCRe1mkMFEltdE97bgztB3tScC4M36ufL1uG/BviCCyQ7AjvJvwWsNYjzkOS5YbxjCcYgHhC5GFwBzkL8TwNZ0ppWUoHDF+EAqfN78Dnd8DJFoZMjKrd5GEOFjg35k9CzbGArvPBHfGfmTW6Lmrp4NI2xPV914xdIMBb7400804t68TLPmVKGzMfj0jd7Kun/z7WFLJ/+kn+ABBkxBxO7WQmAoP3PSKhB/CuGvA/0VQVtD6H9tLkQ9TSu6Djnn6lCRB9kZGOpSkFnaFi2+5ET8d9EPU0xh/EdGs+USLHOCj9Z0iFnX4LkRNQgehWwKZVplBOtY6PH8hRGJVmPl3MBruspzoEVQEtkN3e2Cq79zqDpngz9rWXWo1GauktGwzAmsUyThT8edu+sY07R/WNy/AG2mP2uH9jsbNMhzQ1S/EXVzI="

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

jobs:
  include:

    -   name: 'PHPUnit with PHP 7.2'
        php: 7.2
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small

    -   name: 'PHPUnit with PHP 7.3'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small
        env:
          DEPLOY_JOB: true

    -   name: 'PHPUnit with PHP 7.4'
        php: 7.4
        before_script: composer install -n
        script: vendor/bin/phpunit --testsuite small

    -   name: 'PHPUnit with lowest dependencies'
        php: 7.2
        before_script: composer update --prefer-lowest --prefer-stable -n
        script: vendor/bin/phpunit --testsuite small

#    -   name: 'Runtime tests'
#        php: 7.3
#        before_script:
#          - composer install -n
#          - pip install --user awscli
#          - pip install --user aws-sam-cli
#        script: travis_retry vendor/bin/phpunit --testsuite runtimes
#        # This job is testing the runtimes that are published online, it doesn't make sense to run it on
#        # pull requests and branches, it's more a watchdog than a CI job
#        if: branch = master AND fork = false

    -   name: 'PHPStan'
        php: 7.3
        before_script: composer install -n
        script: vendor/bin/phpstan analyse


deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make docker-images
  skip_cleanup: true
  env:
    DOCKER_BUILD_FLAGS: "--quiet"
  on:
    repo: Nyholm/bref
    tags: true
    all_branches: true
    condition: $DEPLOY_JOB = true