name: Deploy Docker images

on:
  push:
    tags:
      - '*' # On all tags

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Docker login
        run: echo '${{ secrets.dockerPassword }}' | docker login --username ${{ secrets.dockerUsername }} --password-stdin

      - name: Build images
        run: |
          echo "here is the reference:"
          echo $GITHUB_REF
          echo "end of referene"
          cd runtime
#          make docker-images

      - name: Publish
        env:
          DOCKER_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          echo $GITHUB_REF
          echo "here is the DOCKER_TAG:"
          echo $DOCKER_TAG
          echo "end of referene"
#          make publish-docker-images
